import { moment } from "../components/elements";

export default {
  incidentReport: "/incidentReport",
  incidentDashboard: {
    basePath: "/incidentDashboard",
    myDashboard: "myDashboard",
    myDashboard_submitted: `myDashboard?status=2`,
    myDashboard_assinged: `myDashboard?status=3`,
    myDashboard_underInvestigation: `myDashboard?status=4`,
    myDashboard_capaPlanning: `myDashboard?status=5`,
    myDashboard_closureConfirmationSent: `myDashboard?status=6`,
    myDashboard_closureConfirmed: `myDashboard?status=7`,
    myDashboard_irClosure: `myDashboard?status=8`,
    myDashboard_currentMonth: `myDashboard?fromIncidentDateTime=${moment({
      time: new Date().setDate(1),
      format: "YYYY-MM-DD",
    })}&toIncidentDateTime=${moment({
      time: new Date(new Date().getFullYear(), new Date().getMonth() + 1, 0),
      format: "YYYY-MM-DD",
    })}`,
    myDashboard_openSentinelEvent: `myDashboard?typeofInci=8`,
    myDashboard_reportableEvent: `myDashboard?reportable=yes`,
    myDashboard_activeCapaClosure: `myDashboard?capaClosure=active`,
    myDashboard_patientComplaint: `myDashboard?patientYesOrNo=true`,
    myDashboard_beyondAcceptableTat: `myDashboard?tat=beyond`,
    qualityDashboard: "qualityDashboard",
  },
  capaReport: "/capaReport",
  reports: "/reports",
  irConfig: {
    basePath: "/irConfiguration",
    mainConfig: "mainConfig",
    userPermission: "userPermission",
    irDataAnalytics: "irDataAnalytics",
  },
  masters: {
    basePath: "/masters",
    location: "location",
    department: "department",
    category: "categoryAndSubCategory",
    userMaster: "userMaster",
    riskAssessment: "riskAssessment",
    personAffected: "personAffected",
    twoFieldMaster: "twoFieldMaster",
    contributingFactor: "contributingFactor",
    rca: "rca",
    irCodeConfig: "irCodeConfig",
  },
};
